apiVersion: v1
kind: Service
metadata:
  name: career-app-service
spec:
  selector:
    app: career-app
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: api
      protocol: TCP
      port: 4000
      targetPort: 4000
    # - name: api
    #   protocol: TCP
    #   port: 27017
    #   targetPort: 27017
  type: LoadBalancer
